### ISSUE TITLE
Image Dimensions

### ISSUE THREAD

**Issue by hellojere** [elabs/refile#128]
Is there a way to save the image dimension during the upload? 

Dragonfly gem has wonderful "magic" attributes that automatically saves the dimensions if one has the fields "field_width" & "field_height" in the database. 

This solution would be ideal, but if it's impossible, is there any way to get these directly from the Refile rack app?

**Comment by jnicklas** [comment]
No there is no way to do this. The reason being that support for this would have to be built into the JavaScript library, which is pretty tricky to do, and wouldn't be generic in the way that Dragonfly's magic attributes are at all. Different constraints ;). It should be fairly simple to build a controller endpoint which extracts this data, or to extract it in a callback/job on upload.

**Comment by hellojere** [comment]
Understandable. Will have to dig into the callback/job on upload options, as I really really need this in order to switch over from Dragonfly. Thanks anyway.

**Comment by dpehrson** [comment]
Erg, just hit this as well and is pretty annoying. I'm also transitioning from dragonfly and one of the declared scopes on our model narrows down `Photograph`s based on their aspect ratio (any photo that is a square can be an `Avatar`, any 3:2 image can be a lifestyle photo, etc.)

Since I dont use or have any intention to use direct uploads or anything related to the JS library, would it be possible to automagically populate these columns if the data is available?
