### ISSUE TITLE
how I can save files in custom folder?

### ISSUE THREAD

**Issue by eddiefisher** [elabs/refile#139]
how I can save files in custom folder? like:
path = ":table_name/:id/:some_table_column"

**Comment by eddiefisher** [comment]
шеэы

**Comment by rossta** [comment]
I don't believe what you're asking for is currently supported. From the `README`: 

> As you may notice, backends are "flat". Files do not have directories, nor do they have names or permissions, they are only identified by their ID

If you're using the `S3` backend, you can specify a path prefix, but it looks like this would apply to all files, rather than being dynamically based on the model, as your question implies.

**Comment by activestylus** [comment]
This seems like more of an omission than a feature. Namespacing uploads not only helps you to archive and backup projects better, they scale better as you don't have a buttload of files crammed into one spot.

**Comment by jnicklas** [comment]
Of course it's your prerogative to feel that way, but the fact that backend stores are flat addressable is the fundamental cornerstone of Refile design. If you want to have control over the directory structure of your files, then Refile is not for you. That is okay, Refile is very opinionated, so it won't suit everyone's usecase.

I'd like to challenge your assumption though. Why do you *really* need to control the directory structure? `rsync` can do backup for you without having to know the directory structure. AWS can automatically back up to glacier if you're *that* paranoid. If by the scale issue you're thinking of is hitting the file-per-folder limit, then that's pretty easily solvable by using subdirectories, like git's object db does. We don't do that yet (PRs welcome), mostly because I couldn't be bothered to implement it, but we probably should. AWS has no limit on files per prefix in a bucket, so it's not a problem there.

I'd encourage you to think about Refile's backends like git's object database. You don't really need to know how it works internally, and if you don't remember and keep track of what you put into it, then you won't have much fun trying to get anything sensible out of it.

**Comment by activestylus** [comment]
Thanks for the reply jnicklas,

I'd agree that in most cases it's not going to matter to most people. For the scaling bit, since I will be using AWS it's probably not a huge issue. But just to present an odd use-case, my current setup allows me to store all assets at the account level in a multi-tenant app. Part of the selling point of this software is portability, so people could create a zip archive of their account and download. Right now I've conveniently set up all uploads to be scoped by user domain folders.So when they do decide to archive, all the script has to do is add a schema dump to the upload folder, then zip said folder and serve it up.

Technically this is still possible with Refile, though I'd have to do a bit more heavy lifting, probably just iterating over all attachments and copying them into a folder, THEN zipping it.

**Comment by jnicklas** [comment]
That's a really good use-case for putting stuff in sub-directories, I agree. I really don't think it's something we'll ever support out of the box with Refile though. It's just not made for this kind of thing.

**Comment by activestylus** [comment]
Well I managed to work around this shortcoming by simply using Ruby to move files around after upload. While other gems allow me to do this by default, none make uploads (esp with progress bars) as painless as refile. Kind of hard to use anything else now :p

I can't disagree with your general use case, apparently not paying attention to file structure has liberated you to do more interesting things, so more power to ya

**Comment by Eric-Guo** [comment]
Similar to [S3](https://github.com/refile/refile/#1-backend) configure, the correct way to change refile FileSystem store location is using initializers:

```ruby
# config/initializers/refile.rb
Refile.store = Refile::Backend::FileSystem.new(Rails.root.join('public/uploads/refile_store').to_s)
```

**Comment by holden** [comment]
@jnicklas I’ve also drunk from the cool-aid of flat file awesomeness, BUT i also have a multi-tenanted app.  What about when it comes time to calculate storage costs per organization/user?  Does it matter?  I suppose I can use the refile column for file size and then some kind of postgres view of all my files scope by organization?  Or is there an easier way I'm missing?

**Comment by choonkeat** [comment]
> What about when it comes time to calculate storage costs per organization/user?

should add immediately upload & minus upon delete, no?
